#!/usr/bin/env sh

export JDK_DOWNLOAD_URL=https://e344ag.bn.files.1drv.com/y4mr8t_vEep0KMY9omaAgfuxIkL__QJ0K9BftIywFOfY54_nr3mUZpKUIS3d4hybk40K4aQEqyCqVt_Aj9ct3hi_2ywljhTwsJ3TCVAOIdyify-sYw-nK6HhyvrTVlKshmJMA_PyxcFxaCa4UoUF3Y9mF8IfnxdazBgJBo8O_cn-D4IN9i4woDI5UtUvKO72mc8qkzqut0sDoMQ__7O_HUXrw/jdk-8u231-linux-x64.tar.gz

export JCE_DOWNLOAD_URL=https://e345ag.bn.files.1drv.com/y4msP-GXHlkOCC1roJXN9p-tm00PDIlrisUEaea_g8Pv5fjMtHQCAufMksxud997fFC0AiSVYC8RsNpcAC1cXIGsoD9_nTKW2SpjXo48FuFxtF2qyBfX5allKKVdeXWJlhLLEybiJ3fAr9bgti4rMahC-3jPxYFNCilvKj3W3SdUSfflwQ5DD4mu5ssKNN5pZQS0SebrBIu2bFgmgzGrZ8B4A/jce_policy-8.zip

docker build --build-arg JDK_DOWNLOAD_URL="${JDK_DOWNLOAD_URL}" --build-arg JCE_DOWNLOAD_URL="${JCE_DOWNLOAD_URL}" -t $IMAGE_NAME .

